# Copyright © 2020 The OpenEBS Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiva-operator
  namespace: openebs
  labels:
    openebs.io/component-name: jiva-operator
    openebs.io/version: testversion
    name: jiva-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jiva-operator
  template:
    metadata:
      labels:
        name: jiva-operator
        openebs.io/component-name: jiva-operator
        openebs.io/version: testversion
    spec:
      serviceAccountName: jiva-operator
      containers:
        - name: jiva-operator
          # Replace this with the built image name
          image: imageorg/jiva-operator:testimage
          command:
          - jiva-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENEBS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jiva-operator"
            - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
              value: "imageorg/jiva:testimage"
            - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
              value: "imageorg/jiva:testimage"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8282
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
